version: 1.0.{build}
build_script:
- cmd: >-
    git submodule update --init --recursive

    mklink /j 3rd skynet\3rd

    mklink /j lualib-src skynet\lualib-src

    mklink /j service-src skynet\service-src

    mklink /j skynet-src skynet\skynet-src


    echo %PATH%

    Set Path=%path%;C:\MinGW\msys\1.0\bin;C:\MinGW\bin

    mingw-get install mingw32-pthreads-w32-dev

    make